export const DEMO_1_GET_LIST_BEGIN = 'DEMO_1_GET_LIST_BEGIN';
export const DEMO_1_GET_LIST_SUCCESS = 'DEMO_1_GET_LIST_SUCCESS';
export const DEMO_1_GET_LIST_FAILURE = 'DEMO_1_GET_LIST_FAILURE';
export const DEMO_1_GET_LIST_DISMISS_ERROR = 'DEMO_1_GET_LIST_DISMISS_ERROR';
